### ISSUE TITLE
[Question]: PR-> CR -> PR?

### ISSUE THREAD

**Issue by ccctingting** [kaigu1990/stabiot#37]
I think if a PR->CR->PR occurs, data queries should be raised, and it should not be interpreted as PR. However, the current program seems to treat it as PR.

**Comment by kaigu1990** [comment]
Yes, in current program, I generate PR for this scenario. Basically I know this is a data issue that should be addressed rather than just interpreted as PR. In other words, this case should not have occurred, so I'm not sure how to handle it in the analysis function.
Because it's also not reasonable to leave the NA in the output, do you have some advice for this question?
One option I can think of is to add a warning when PR->CR->PR is detected but the cBOR is still kept as PR.

**Comment by ccctingting** [comment]
What about add a warning "Please query data" if a PR or SD occurs after a CR, regardless of how many NEs are between them?

**Comment by kaigu1990** [comment]
Yeah, that's a good solution. I will update this case along with issue #36 .

**Comment by kaigu1990** [comment]
One warning was added. If there are no additional issues, I will merge this branch into the main.
https://github.com/kaigu1990/stabiot/blob/afccd0a2c7217acd4c8ca418313a1fa512b4c428/R/onco_resp.R#L156-L168

**Comment by kaigu1990** [comment]
Thanks for your suggestion, this issue has been solved and merged into main branch.
